{
 "title": "Home Energy Usage v2",
 "description": "A dashboard that shows your home energy usage. Using Prometheus, Home Assistant and the Emporia Vue 2.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Top 5 Devices Currently Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(topk(5,(homeassistant_sensor_power_w{friendly_name!~\".*Total.*\"} > 5)))",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Current Month Total Power Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh{friendly_name=\"Freels Vue Balance 1MON\"}"
    }
   ]
  },
  {
   "title": "Current Month Bill ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_energy_kwh{friendly_name=\"Total Power 1Mon\"} * .0965 ) * 1.05 + 14"
    }
   ]
  },
  {
   "title": "Current Day Power Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh{friendly_name=\"Total Power 1D\"}"
    }
   ]
  },
  {
   "title": "Current Day Power Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh{friendly_name=\"Total Power 1D\"} * .0965"
    }
   ]
  },
  {
   "title": "Month Power Total",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh{friendly_name=~\".*1M.*\"} and homeassistant_sensor_energy_kwh{friendly_name!~\".*Total.*|.*Power.*|.*Freels.*|.*Bedroom #2.*\"}",
     "legendFormat": "{{friendly_name}} "
    }
   ]
  },
  {
   "title": "Hourly Power by Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time(homeassistant_sensor_power_w{friendly_name!~\".*Total.*\"}[60m]) /4",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Devices Last Week",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(5,sum by (friendly_name) (increase(homeassistant_sensor_energy_kwh{friendly_name!~\".*Total.*|.*Mon.*\"}[7d] )) )",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Daily Power Usage ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh{friendly_name=\"Total Power 1D\"} ",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Power Spikes This Week",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(homeassistant_sensor_energy_kwh{friendly_name=\"Total Power 1D\"}[1h])",
     "legendFormat": " Rate of Power"
    }
   ]
  }
 ]
}