{
 "title": "Node Exporter",
 "time": { "from": "2026-08-05T11:49:02.000Z", "to": "now" },
 "panels": [
  {
   "title": "Free Disk",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n    1 -\r\n    (\r\n        node_memory_MemAvailable_bytes\r\n        /\r\n        node_memory_MemTotal_bytes\r\n    )\r\n) * 100",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "100 -\r\n(\r\n    node_filesystem_avail_bytes{\r\n        fstype!=\"tmpfs\",\r\n        mountpoint=\"/\"\r\n    }\r\n    /\r\n    node_filesystem_size_bytes{\r\n        fstype!=\"tmpfs\",\r\n        mountpoint=\"/\"\r\n    }\r\n    *100\r\n)",
     "legendFormat": "Disk Usage"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\r\n    avg by(instance)(\r\n        rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\r\n    ) * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Transit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{\r\n  device!~\"^(lo|docker0|br-.*|veth.*)$\"\r\n}[1m])",
     "legendFormat": "Receive (bytes_total)"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{\r\n  device!~\"^(lo|docker0|br-.*|veth.*)$\"\r\n}[1m])",
     "legendFormat": "Transmit (bytes_total)"
    }
   ]
  },
  {
   "title": "Node Load (5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "node_load5", "legendFormat": "__auto" }
   ]
  }
 ]
}