global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  # if node-exporter
  - job_name: node-exporter
    static_configs:
      - targets:
          - host.docker.internal:9100
  - job_name: omv
    static_configs:
      - targets:
          - 192.168.1.107:9100
  
  # # if node-exporter in RPi
  # - job_name: raspberrypi
  #   static_configs:
  #     - targets:
  #         - 192.168.1.xxx:9100

  # if cadvisor
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  # if proxmox-exporter
  - job_name: proxmox
    metrics_path: /pve

    params:
      module:
        - default
      cluster:
        - "1"
      node:
        - "1"

    static_configs:
      - targets:
          - 192.168.1.200

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: pve-exporter:9221

  # if UPS NUT exporter
  - job_name: "nut"
    static_configs:
      - targets:
          - "192.168.1.200:3493"

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: nut-exporter:9995

