services:
  prometheus:
    image: prom/prometheus:v3.5.0
    restart: unless-stopped

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"

    ports:
      - "9090:9090"

    volumes:
      - /mnt/omv/.infra/docker/prometheus/data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 5s
      retries: 3

    networks:
      - monitoring

  grafana:
    image: grafana/grafana:12.2.0
    restart: unless-stopped

    depends_on:
      prometheus:
        condition: service_healthy

    environment:
      TZ: ${TZ}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}

    ports:
      - "3000:3000"

    volumes:
      - /mnt/omv/.infra/docker/grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3

    networks:
      - monitoring

networks:
  monitoring:
    external: true

  backend:
    external: true